/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 *****************************************************************************/

#include <stdint.h>
#include "NVIC.h"
#include "SCB.h"

static volatile uint32_t USART2_IRQHandlerFlag = 0;

int main(void)
{
	SCB_SetPriorityGrouping(SCB_PRIORITYGROUP_2);

	NVIC_EnableIRQ(USART2_IRQn);
	NVIC_SetPendingIRQ(USART2_IRQn);

	NVIC_DisableIRQ(USART2_IRQn);

    /* Loop forever */
	for(;;);
}

void USART2_IRQHandler(void)
{
	USART2_IRQHandlerFlag = 1;
}
